#! /usr/bin/env bash
################################################################################
# Copyright (c) 2012 Los Alamos National Security, LLC
# All rights reserved.
################################################################################

#------------------------------------------------------------------------------#
# Usage: bootstrap <mode>
#
# If mode is set to devel, the sandbox directory is added to the build.
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
# Generate configure.ac file
#------------------------------------------------------------------------------#
echo "Generating configure.ac"
config/create_configure_ac $1 > configure.ac

#------------------------------------------------------------------------------#
# Generate Makefile.am in lib directory
#------------------------------------------------------------------------------#
echo "Generating lib/Makefile.am"
[ ! -d lib ] && mkdir lib
config/create_lib_am > lib/Makefile.am

#------------------------------------------------------------------------------#
# Call libtoolize
#------------------------------------------------------------------------------#
echo "Calling libtoolize..."
# check for glibtoolize
glibtoolize --version &> /dev/null && LIBTOOLIZE=glibtoolize || LIBTOOLIZE=libtoolize

# actually call libtoolize
$LIBTOOLIZE -c -f --automake

#------------------------------------------------------------------------------#
# Call aclocal to generate m4 file
#------------------------------------------------------------------------------#
echo "Calling aclocal -I m4"
aclocal -I m4 > /dev/null 2>&1

#------------------------------------------------------------------------------#
# Run python script to generate autotest files
#------------------------------------------------------------------------------#

echo "Calling python testboot.py"
python config/testboot.py

#------------------------------------------------------------------------------#
# Call autoheader
#------------------------------------------------------------------------------#
#echo "Calling autoheader"
#autoheader

#------------------------------------------------------------------------------#
# Call automake
#------------------------------------------------------------------------------#
echo "Calling automake -af --foreign"
automake -af --foreign -c

#------------------------------------------------------------------------------#
# Call autoconf
#------------------------------------------------------------------------------#
echo "Calling autoconf"
autoconf
