#! /usr/bin/env bash
################################################################################
# Copyright (c) 2012 Los Alamos National Security, LLC
# All rights reserved.
################################################################################

#------------------------------------------------------------------------------#
# Generate configure.ac file
#------------------------------------------------------------------------------#
echo "Generating configure.ac"
config/create_configure_ac > configure.ac

#------------------------------------------------------------------------------#
# Generate Makefile.am in lib directory
#------------------------------------------------------------------------------#
echo "Generating lib/Makefile.am"
[ ! -f lib ] && mkdir lib
config/create_lib_am > lib/Makefile.am

#------------------------------------------------------------------------------#
# Create symbolic links in project include directory
#------------------------------------------------------------------------------#
#echo "Creating links"
#config/create_links

#------------------------------------------------------------------------------#
# Call libtoolize
#------------------------------------------------------------------------------#
echo "Calling libtoolize..."
# check for glibtoolize
glibtoolize --version &> /dev/null && LIBTOOLIZE=glibtoolize || LIBTOOLIZE=libtoolize

# older versions of libtoolize use configure.in
$LIBTOOLIZE -c -n -f --automake &> /dev/null || ln -s configure.ac configure.in

# actually call libtoolize
$LIBTOOLIZE -c -f --automake

#------------------------------------------------------------------------------#
# Call aclocal to generate m4 file
#------------------------------------------------------------------------------#
echo "Calling aclocal -I m4"
aclocal -I m4 > /dev/null 2>&1

#------------------------------------------------------------------------------#
# Run python script to generate autotest files
#------------------------------------------------------------------------------#

echo "Calling python testboot.py"
python config/testboot.py

#------------------------------------------------------------------------------#
# Call automake
#------------------------------------------------------------------------------#
echo "Calling automake -af --foreign"
automake -af --foreign -c

#------------------------------------------------------------------------------#
# Call autoconf
#------------------------------------------------------------------------------#
echo "Calling autoconf"
autoconf
