#! /usr/bin/env bash
################################################################################
# Copyright (c) 2012 Los Alamos National Security, LLC
# All rights reserved.
################################################################################

# create version
echo VERSION_TAG=`config/make_version` > config/version

# filter input
#cat configure.in.ac | config/filter_configure_ac > configure.ac
cat configure.in.ac | config/filter_configure_ac $1
