#! /usr/bin/env bash
################################################################################
# Copyright (c) 2012 Los Alamos National Security, LLC
# All rights reserved.
################################################################################

# source version information
echo VERSION_TAG=`config/make_version` > config/version
. config/version

# filter input
cat configure.in.ac | sed "s,VERSION_TAG,$VERSION_TAG,g" > configure.ac
