#! /usr/bin/env bash
################################################################################
# Copyright (c) 2012 Los Alamos National Security, LLC
# All rights reserved.
################################################################################

# get the latest tag
tag=`git tag | head -n 1`

# build will count the number of commits since the tag
build=`git log tags/$tag | grep commit | wc -l`

echo $tag"."$build
