#! /usr/bin/env bash
################################################################################
# Copyright (c) 2012 Los Alamos National Security, LLC
# All rights reserved.
################################################################################

tag=`git tag | head -n 1`

major=`echo $tag| sed 's,\..*$,,g'`
minor=`echo $tag | sed 's,^.*\.,,g'`
build=`git log tags/$tag | grep commit | wc -l`

echo $major"."$minor"."$build
